// <auto-generated />
using System;
using AnchapaxiAriel_ExamenP1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnchapaxiAriel_ExamenP1.Migrations
{
    [DbContext(typeof(AnchapaxiAriel_ExamenP1Context))]
    partial class AnchapaxiAriel_ExamenP1ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnchapaxiAriel_ExamenP1.Models.AnchapaxiModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateOnly>("BirthDay")
                        .HasColumnType("date");

                    b.Property<bool>("IsStudent")
                        .HasColumnType("bit");

                    b.Property<float>("MoneyInTheBank")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PhoneId")
                        .HasColumnType("int");

                    b.Property<int>("idPhone")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PhoneId");

                    b.ToTable("AnchapaxiModel");
                });

            modelBuilder.Entity("AnchapaxiAriel_ExamenP1.Models.PhoneModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PhoneModel");
                });

            modelBuilder.Entity("AnchapaxiAriel_ExamenP1.Models.AnchapaxiModel", b =>
                {
                    b.HasOne("AnchapaxiAriel_ExamenP1.Models.PhoneModel", "Phone")
                        .WithMany()
                        .HasForeignKey("PhoneId");

                    b.Navigation("Phone");
                });
#pragma warning restore 612, 618
        }
    }
}
